"""
Presentation Adapters for MCP presentation tool calls.

Provides:
- PresentationAdapterProtocol
- LocalPresentationAdapter (uses python-pptx to generate real slides)
- MockPresentationAdapter (in-memory adapter for testing without external deps)
"""
from __future__ import annotations

import os
import uuid
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from app.observability.logging import get_logger

logger = get_logger(__name__)


@runtime_checkable
class PresentationAdapterProtocol(Protocol):
    """Protocol for presentation generation adapters."""

    async def execute_tool(self, tool_name: str, arguments: dict[str, Any]) -> dict[str, Any]:
        """Execute an allowlisted presentation operation."""
        ...


class MockPresentationAdapter:
    """
    Mock adapter with identical interface for testing and isolated verification.
    """

    def __init__(self) -> None:
        self.presentations: dict[str, dict[str, Any]] = {}

    async def execute_tool(self, tool_name: str, arguments: dict[str, Any]) -> dict[str, Any]:
        match tool_name:
            case "create_presentation":
                pres_id = arguments.get("presentation_id") or f"pres_{uuid.uuid4().hex[:8]}"
                self.presentations[pres_id] = {
                    "presentation_id": pres_id,
                    "title": arguments["title"],
                    "subtitle": arguments.get("subtitle", ""),
                    "slides": [],
                }
                return {"presentation_id": pres_id, "status": "created"}

            case "add_slide":
                pres_id = arguments["presentation_id"]
                pres = self.presentations.setdefault(pres_id, {"slides": []})
                slide = {
                    "title": arguments["title"],
                    "content": arguments.get("content", []),
                }
                pres["slides"].append(slide)
                return {"presentation_id": pres_id, "slide_index": len(pres["slides"]) - 1}

            case "add_title":
                pres_id = arguments["presentation_id"]
                if pres_id in self.presentations:
                    self.presentations[pres_id]["title"] = arguments["title"]
                return {"presentation_id": pres_id, "status": "title_updated"}

            case "add_content":
                pres_id = arguments["presentation_id"]
                return {"presentation_id": pres_id, "status": "content_added"}

            case "export_pptx":
                pres_id = arguments["presentation_id"]
                pres = self.presentations.get(pres_id, {"slides": []})
                return {
                    "presentation_id": pres_id,
                    "status": "exported",
                    "file_path": f"/tmp/exports/{pres_id}.pptx",
                    "file_size_bytes": 1024 * (len(pres.get("slides", [])) + 1),
                    "slide_count": len(pres.get("slides", [])),
                }

            case _:
                return {"status": "unhandled"}


class LocalPresentationAdapter:
    """
    Real slide generation adapter utilizing python-pptx.
    Generates professional PPTX decks.
    """

    def __init__(self, output_dir: str = "/tmp/sales_presentations") -> None:
        self._output_dir = Path(output_dir)
        self._output_dir.mkdir(parents=True, exist_ok=True)
        self._active_decks: dict[str, Any] = {}
        self._deck_metadata: dict[str, dict[str, Any]] = {}

    async def execute_tool(self, tool_name: str, arguments: dict[str, Any]) -> dict[str, Any]:
        from pptx import Presentation
        from pptx.util import Inches, Pt

        match tool_name:
            case "create_presentation":
                pres_id = arguments.get("presentation_id") or f"pres_{uuid.uuid4().hex[:8]}"
                prs = Presentation()
                # Title slide layout (0)
                title_slide_layout = prs.slide_layouts[0]
                slide = prs.slides.add_slide(title_slide_layout)
                title = slide.shapes.title
                subtitle = slide.placeholders[1]

                title.text = arguments["title"]
                subtitle.text = arguments.get("subtitle", "Generated by SalesFlow Intelligence")

                self._active_decks[pres_id] = prs
                self._deck_metadata[pres_id] = {
                    "presentation_id": pres_id,
                    "title": arguments["title"],
                    "slide_count": 1,
                }
                return {"presentation_id": pres_id, "status": "created"}

            case "add_slide":
                pres_id = arguments["presentation_id"]
                prs = self._active_decks.get(pres_id)
                if not prs:
                    prs = Presentation()
                    self._active_decks[pres_id] = prs
                    self._deck_metadata[pres_id] = {"presentation_id": pres_id, "slide_count": 0}

                # Title and Content layout (1)
                bullet_slide_layout = prs.slide_layouts[1]
                slide = prs.slides.add_slide(bullet_slide_layout)
                shapes = slide.shapes
                title_shape = shapes.title
                body_shape = shapes.placeholders[1]

                title_shape.text = arguments["title"]
                tf = body_shape.text_frame

                contents = arguments.get("content", [])
                if isinstance(contents, str):
                    contents = [contents]

                for idx, item in enumerate(contents):
                    if idx == 0:
                        tf.text = str(item)
                    else:
                        p = tf.add_paragraph()
                        p.text = str(item)
                        p.level = 0

                self._deck_metadata[pres_id]["slide_count"] += 1
                return {
                    "presentation_id": pres_id,
                    "slide_count": self._deck_metadata[pres_id]["slide_count"],
                }

            case "export_pptx":
                pres_id = arguments["presentation_id"]
                prs = self._active_decks.get(pres_id)
                if not prs:
                    prs = Presentation()

                file_path = self._output_dir / f"{pres_id}.pptx"
                prs.save(str(file_path))
                file_size = file_path.stat().st_size
                slide_count = self._deck_metadata.get(pres_id, {}).get("slide_count", len(prs.slides))

                return {
                    "presentation_id": pres_id,
                    "status": "exported",
                    "file_path": str(file_path),
                    "file_size_bytes": file_size,
                    "slide_count": slide_count,
                }

            case _:
                return {"status": "ok"}
